### ISSUE TITLE
ckeditor 原始碼瀏覽

### ISSUE THREAD

**Issue by geek01** [tad0616/tadtools#4]
因為習慣使用原始碼編輯，ckeditor原始碼瀏覽有點不友善，我常在sublime編輯完再貼回去，後來找到CodeMirror這個plugin，原始碼有了Hightlight，找錯或重編輯清楚多了，所以私心建議可以在ckeditor加入這個實用的plugin~

http://ckeditor.com/addon/codemirror

**Comment by tad0616** [comment]
沒問題！我研究一下！

**Comment by geek01** [comment]
老師動作真快，感恩～
